### ISSUE TITLE
When grouping a selection of BlElement, the order is not the same

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#103]
Create two elements and group them.
The group contents have child but not in the same order that the selection.

**Comment by Nyan11** [comment]
Probably fix when i updated the Tree element in #110. Need testing

**Comment by Nyan11** [comment]
No it does not work

**Comment by Nyan11** [comment]
Group command memento should not create new BlElement but instead recycle previously destroyed ones.

**Comment by Nyan11** [comment]
New questions, how to test that no new reference are created by undo / redo memento ?

**Comment by Nyan11** [comment]
#131 is merged
