### ISSUE TITLE
Display BlElement id at first in the Tree

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#109]
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/1bd9d67f-7a15-4f80-b139-2c5a0210e34c)

The problem is that ids are not visible when the Tree is reduce.
Ids are important to navigate into the Tree, so I propose to have this order for a BlElement line : 
1 - Icon
2 - Id in white 
3 - Classname (in gray)
4 - Hash number (in gray)

**Comment by labordep** [comment]
@Nyan11 I have updated columns, but when the tree is very small the id value is hidden by class value :( 
Do you know if this is possible to setup the layout of the line ?

**Comment by Nyan11** [comment]
I was trying to do this one too

**Comment by Nyan11** [comment]
You can set a fix width

**Comment by labordep** [comment]
I cannot spend a lot of time for Spec stuff, so do you think this is not possible without notified Spec team ?

**Comment by Nyan11** [comment]
Is editing the ID directly in the tree necessary ?

**Comment by labordep** [comment]
I don't know, I'm asking about that, but I think that it should be dangerous to directly edit, may be a double click to edit is better.

**Comment by Nyan11** [comment]
i can deactivate the edit in tree for now. I hink i can easily put the ID before if i do that.
Is the classname necessary ? we already have the icon to represent the class.
