### ISSUE TITLE
Toolbar: meanings?

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#11]
Hi, great tool! I wonder what's the meaning of these buttons. Can I turn on labels, or they should have tooltips when the cursor is over.

<img width="424" alt="Screenshot 2023-07-05 at 12 41 20" src="https://github.com/OpenSmock/Pyramid/assets/3044265/2ae664a4-c8a2-4dba-b1ec-7f5a8d03334d">

**Comment by labordep** [comment]
Thanks @tinchodias for your feedback. 
You're all right, we will add some tooltips.
1 - "Show / hide left panel"
2 - "Save project"
3 - "Project configuration"
4 - "Refresh space in case of an issue"
5 - "Undo"
6 - "Redo"
7 - "Show / hide right panel"

**Comment by tinchodias** [comment]
A bit unrelated but...
did you consider adding a Browse button, to open a system browser on the method? maybe I already added another issue for this

**Comment by labordep** [comment]
> A bit unrelated but... did you consider adding a Browse button, to open a system browser on the method? maybe I already added another issue for this

Yes this in our roadmap :D

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/17
