### ISSUE TITLE
Put/Send actions confusions between these actions and icons direction

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#110]
Create a group in a group and add a text and an element. 
The actions Put/Send are not clear and there is a confusions between them for a beginner.

https://github.com/OpenSmock/Pyramid/assets/49183340/d8361370-b80c-450b-9c71-9a7ad32db5b1

I propose these items with icon orientation (same as actual) but with different actions as tooltip for menu button : 
- //\\   First = Set the element as the first child in the child list of his parent. Child is display in the back for the same elevation level.
-  / \   Up = Set the element before the previous one in the child list of his parent.
-  \ /   Down = Set the element after the next one in the child list of his parent.
- \\//   Last = Set the element as the last child in the child list of his parent. Child is display in the front for the same elevation level.

This is imporant to have same color for all these icons.

@Nyan11 do you confirm that these actions doesn't modify the elevation property ?

**Comment by Nyan11** [comment]
These actions modify the elevation property but not always.

Bloc store the children elements in an ordered collction.

The drawing sequence is done by drawing the element with thehighest elevation.
In case of a conflict, two elements with the same elevation, bloc will draw first the element with the smallest index of the list (i.e. the element added first).

The Pyramid command (Top, Up, Down, Bottom) will try to change the order of the elements in the list to modify the drawing sequence but there are some cases where it also need to change the elevation.

For example:

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/ba28ec12-1af2-45a6-9429-df0a833249ab)

All three squares belong to the same parent.
* Red has an elevation of 0 and is first in the ordered collection.
* Blue has an elevation of 1 and is second in the ordered collection.
* Green has an elevation of 2 and is last in the ordered collection.

If i send the command "send up" to Green, The Red elevation will change from 1 to 2 (To be on the same level as Blue), and will switch it's position with Blue in the collection to be render after Blue.

Personally i found very confusing to have two differents systems to represent the drawing sequence (elevation, and order in the list).

**Comment by Nyan11** [comment]
Plus in the example,

If we now use the command "send down" to Green, Green will just swap position with Blue, but keep it's elevation at 2.

We loose the information about the elevation.

**Comment by Nyan11** [comment]
I see elevation more has a sort of group of "drawing sequence" and the order in the collection has the "drawing sequence" but it is really confusing.

**Comment by labordep** [comment]
Thanks @Nyan11 for your feedback. If I understood the "z" order property is different than the "elevation" property which is the order in the child list ?

**Comment by Nyan11** [comment]
Z index = BlElevation

The drawing sequence follows the rules:

1. The children are drawn on top of their  parent.

2. The child with the highest z index (or elevation) is drawn on top of the other children.

3. If multiples elements have the same z index, then the children index is taken into account.

You have two differents properties to change the drawing sequence:

The elevation (z index or BlElevation) and the index position in the parent's children collection.

**Comment by labordep** [comment]
Ok great ! So we need to be very clear on what we edit.
First I want to edit the order : this is most basic case (for 2D library): the paint order in a tree branch (parent).
Second, I want to edit the z index, this is most used in 3D library but usefull for us.

The difficulty is to present a clear state of these two property to identity bugs or problems.

**Comment by labordep** [comment]
@Nyan11 I'm starting to write a plugin for that.

**Comment by labordep** [comment]
If z value = 0 : don't cannot display it in the cell.

**Comment by Nyan11** [comment]
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/b920dd36-18c7-4728-a2d3-e007882e2241)

**Comment by Nyan11** [comment]
ok with 124
