### ISSUE TITLE
Feature: Project test mode

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#113]
The idea is to test the current edited project.
It should be a button to switch between edition mode and test mode.
We can cover two cases: 
- First - Direct test inside the editor view, click on a switch button to "test mode" and use the mouse (or the keyboard) to test the current projet. Go back to edition mode to edit the project content.
- Second - A play mode: the idea is to propose to open the project in a dedicated window to test it in a real situation. This can be a play button which is opening a new window with the current project instanciation. If the project already cames from an existing running view (edition) this play button open a new window in addition of the existing view, not a replacement. 
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/e0f3163a-372a-4f73-bfa1-eaec1ca2fef8)

**Comment by labordep** [comment]
See #113

**Comment by labordep** [comment]
@Nyan11 I initialize a branch to do that, do you think that I have the good approach (of course this is dirty) or not ?

**Comment by Nyan11** [comment]
Yes i like to create a new branch before each development. I do all my commit / testing on it. And when it's ready i submit a pull request. This way it's easy for a reviewer to check on it.

**Comment by Nyan11** [comment]
Plus if for some reason you are block, you can always commit everything you have and take another ticket while waiting for inspiration to come.

**Comment by labordep** [comment]
Oups sorry @Nyan11 but I made a confusion, my answer was about the issue solution :) But ok working in a branch is good :)

**Comment by Nyan11** [comment]
Should work on new pull request

**Comment by Nyan11** [comment]
First is ok with 125.

Second todo, maybe open a new ticket for second ?

(A play mode: the idea is to propose to open the project in a dedicated window to test it in a real situation. This can be a play button which is opening a new window with the current project instanciation. If the project already cames from an existing running view (edition) this play button open a new window in addition of the existing view, not a replacement.)

**Comment by labordep** [comment]
Yep, I'll create a new issue for the second point.

**Comment by Nyan11** [comment]
ok because #129 issue is open
