### ISSUE TITLE
Instance of PyramidProjectModel did not understand #roots

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#126]
Open Pyramid and add a new element on the root :

![image](https://github.com/OpenSmock/Pyramid/assets/49183340/25b90824-e257-4f9e-8083-f34ecebf78dd)

@Nyan11 I have also this problem in two tests:
- `PyramidEditorTest>>testOpenFromBlSpace`
- `PyramidEditorTest>>testOpenFromBlSpaceWithSpacePluginUninstalled`

These tests are not executed in the github CI. We need to write a test with the same reproductible problem without GUI (can be executed on CI).

My config:
- Pharo 11 latest
- Windows 11 Pro

**Comment by labordep** [comment]
A big capture with the editor in background: 

![image](https://github.com/OpenSmock/Pyramid/assets/49183340/0927e45e-e538-4c05-b808-c80784e5f0f9)

**Comment by Nyan11** [comment]
i renamed roots by firstLevelElements. I don't know why i miss this one

**Comment by Nyan11** [comment]
Missing tests but will be done in #130
