### ISSUE TITLE
pySTON pragma?

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#13]
I saved my project and browsed the method `<pySTON>` pragma. It makes me wonder what is its utility.

**Comment by Nyan11** [comment]
Hello,

PySton pragma is used by `PyramidVisualPystonForCly`.

`PyramidVisualPystonForCly` is an extension of Calypso browser, i use it to display inside the browser a preview of the serialized design.

**Comment by labordep** [comment]
Preview example :
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/77173d25-50b8-4dbd-ab8d-e7acff645a42)

**Comment by labordep** [comment]
But I think that the tab name is not good. 
May be "Pyramid preview" is better.
And "Open" => "Open in new Space"

**Comment by tinchodias** [comment]
Excellent, thanks!

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/34
