### ISSUE TITLE
Cannot setup element border

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#139]
Hi @Nyan11, I cannot edit the border of a BlElement in the properties tab.
Is it a bug or a miss ?

I can do that manually in the Pyramid playground (thanks to it):
`self border: (BlBorder empty)`

**Comment by Nyan11** [comment]
I have not yet developped the feature.

There are multiple informations behind a border:

- [ ] Paint selection (solid / gradient / image / transparent + associated paint input)
- [ ] Join (3 choices)
- [ ] Caps (3 choices)
- [ ] Spacing (array of n floating number)

Also BlBorder is a complicated object where you have to use a BlBorderBuilder to modify (and is the only object in Bloc where you need a dedicated builder to make).

**Comment by Nyan11** [comment]
See branch alpha5
