### ISSUE TITLE
Enhance the image by setting it as a background

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#140]
Ways for users to use images on a Pyramid project:

1 - Use the playground to do the job manually (developper responsibility)
2 - Import an image as a BlElement using the editor UI

- Click "Add new element" and select `Image` in the library menu
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/eabfaff3-fb28-437f-ae55-211331cf93d5)
A setup window open and propose theses different ways to import an image as a BlElement:
  - Import from file (the image bitmap is completely serialized)
  - [Possible ?] Relative link from file (the image is loaded on the fly and we serialize only the **relative** filepath)
  - Use Form in existing Class/method, for example: `MyClass myImage` (the image is loaded on the fly and we serialize only the class/method association)
  - [May be later] Paste from clipboard (same serialization of the first way)
  - Others ??

In all cases there is a BlElement with a image as a background, when the element is added and selected this is the same way to modifiy the image in the properties tab :

- Go to background setup and choose same options that describes in point 1:
  - Show the current image (read-only), actually in the property tab is it ok 
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/01dba9e2-8871-40b3-a926-d6204c51ce58)
but not always in the background window
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/ecc624f9-b2eb-4ab2-92ba-49608e3e1afc)
  - Display how the image is setting up (bitmap, link, class/method, etc.)
  - Possibility to change

**Comment by labordep** [comment]
@Nyan11 I think there is a similar problem in Toplo. For example, how to store a button icon ?

**Comment by Nyan11** [comment]
Yes, I am making an Input that will work with the command to change the background and the command to set an icon. This way i can reuse the code/gui for the two use-cases
