### ISSUE TITLE
Error when starting morphic BlSpace

### ISSUE THREAD

**Issue by ELePors** [OpenSmock/Pyramid#148]
When starting a Demo with a Morphic BlSpace.
The stack call to the **_canEditSpace_:** on **_PyramidPluginEditOnRunning_** produces a doesNotUnderstand exception on my BlSpace which does not knows the **_userData_** accessor.

The starting point is here :
```Smalltalk
bl := BlElement new.
host := BlMorphicWindowHost new.
	BlSpace new
		in: [ :sp | sp root addChild: bl ];
		host: host;
		title: host asString;
		extent: 500 @ 250;
		show.
```

**Comment by Nyan11** [comment]
I do not understand the problem.

BlSpace can perform `#userData`.

**Comment by labordep** [comment]
This is a problem due to an old Bloc version (https://github.com/OpenSmock/Bloc/releases/tag/1.0.0.2). 
If necessary we can create a specific branch of Pyramid to support this version.
