### ISSUE TITLE
Use sequential identifiers? 

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#16]
<img width="462" alt="Screenshot 2023-07-05 at 13 24 14" src="https://github.com/OpenSmock/Pyramid/assets/3044265/ba3bfa2d-fbc0-44f3-b642-b75f0ccd17d7">

I just realized that when I changed the background to orange, the identifier didn't change automatically which makes totally sense, as not every color as a name, etc. But I didn't realize of that at first... so maybe (my suggestion) it's preferable create identifiers that user doesn't associate with the background color. 

Consider this example of `Generator` that always answers a new string:

```
alphabetGenerator := Generator on: [ :generator |
		| index |
		index := 1.
		[ 	Character alphabet do: [ :each |
				| next suffix |
				next := each asUppercase asString.
				suffix := index = 1
					ifTrue: [ '' ]
					ifFalse: [ index asString ].
				generator yield: next, suffix ].
			index := index + 1 ] repeat ].
```
The generators can be used like a read stream, via `next` or with `next:` to get a collection, like this:
```
alphabetGenerator next: 50. "an OrderedCollection('A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O'
'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z' 'A2' 'B2' 'C2' 'D2'
'E2' 'F2' 'G2' 'H2' 'I2' 'J2' 'K2' 'L2' 'M2' 'N2' 'O2' 'P2'
'Q2' 'R2' 'S2' 'T2' 'U2' 'V2' 'W2' 'X2')"
```

**Comment by tinchodias** [comment]
Bah, the identifier could be also calculated like `(collectionOfAllElementsInTheSpace size + 1) asString`, but personally I liked more alphabet char + number as in the generator, and had the snippet at hand so I proposed it. But any sequence is okay :p

**Comment by labordep** [comment]
@tinchodias that's a good idea !
Even if our creation panel is temporary I think we need to rewrite the id generation for avoid confusion. Especially during demos.
In term we can have some strategy to propose different/default id such as a prefix or a suffix, etc.
For now we will use your generator to create not confusing ids :)

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/33
