### ISSUE TITLE
Relaunching the application

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Pyramid#29]
Creating a new Pyramid project, then closing the Pharo image while saving it and then relaunching the aforementioned image creates an error titled "Instance of BlMorphicEventHandler did not understand #handleTextEditionEvent:"

**Comment by labordep** [comment]
@Eliott-Guevel can you precise your configuration ?

**Comment by labordep** [comment]
![image](https://github.com/OpenSmock/Pyramid/assets/49183340/3a0b98dd-dd5f-4f1f-b1e3-056b2407c6c7)

I have the problem in my configuration : 
- Windows 11 Pro
- Pharo 11 build.707
- VM 10.0.7.0

**Comment by Nyan11** [comment]
Text Edtion Event is an event generated by SDL2. SDL2 create the window displayed by the OS.

Text edition is a special event that is trigger when you use your OS with Japanese or Chiness keyboard.
https://wiki.libsdl.org/SDL2/Tutorials-TextInput

Text Edition is on the Spot in SDL2
https://www-archive.mozilla.org/projects/intl/input-method-spec.html

**Comment by Nyan11** [comment]
Every time the Pharo window loose it's focus and regain it, a `SDL_TextEditingEvent` is trigger

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/assets/34318678/63282060-1ebd-4b6b-9254-6b8dbef781cf

**Comment by labordep** [comment]
Thanks @Nyan11.
@tinchodias may be you have already seen this problem ?

**Comment by tinchodias** [comment]
Interesting, but no, I didn't know about this. Thanks for reporting

**Comment by Nyan11** [comment]
https://github.com/pharo-graphics/Bloc/pull/336 is merged.
I Check, i didn't manqage to reproduce the code so it should be ok.
