### ISSUE TITLE
Update window title

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#5]
Setup the default title of a Pyramid Window as : 
- New UI : "New project | Pyramid"
- When the project is currently loaded or saved in a Class : "[Class] class >> [method] | Pyramid"

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/17

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/pull/17
