### ISSUE TITLE
IDE package should be loaded manually?

### ISSUE THREAD

**Issue by tinchodias** [OpenSmock/Pyramid#8]
I loaded in a new Pharo 11 with:
```
Metacello new
	baseline: 'Pyramid';
	repository: 'github://OpenSmock/Pyramid:main/src';
	load
```
and the world menu on top didn't have the Pyramic entry, but it appeared when I loaded the IDE package via Iceberg.

I guess the baseline needs to include it?

BTW: Awesome project!

**Comment by labordep** [comment]
Thanks @tinchodias  :)
This is a bug :(

**Comment by labordep** [comment]
Fixed
