### ISSUE TITLE
Provide Plugin guide in English

### ISSUE THREAD

**Issue by astares** [OpenSmock/Pyramid#80]
The plugin guide is in french, but should be in english

https://github.com/OpenSmock/Pyramid/wiki/Ajouter-un-nouveau-plugin-a-Pyramid

**Comment by Nyan11** [comment]
https://github.com/OpenSmock/Pyramid/wiki/Add-a-new-plugin-to-Pyramid

**Comment by astares** [comment]
Great, thanks!
