### ISSUE TITLE
CI bug

### ISSUE THREAD

**Issue by Nyan11** [OpenSmock/Pyramid#87]
# Timeout

CI timeout before it end testing on Pharo 12. The timeout is define in `.github/workflows/Pharo11CI.yml` at the #timeout-minutes: 10
> I suggest we put it at 15 min. It seem that Pharo12 CI takes between 7 to 10 min to complete.

# SSH before HTTPS

Matecello try to download the package with SSH protocole, but doesn't have a SSH key, so it fails but then it try HTTPS.

```txt
MetacelloNotification: Loading baseline of BaselineOfPyramid...
aborting
I got an error while cloning: There was an authentication error while trying to execute the operation: . 
This happens usually because you didn't provide a valid set of credentials. 
You may fix this problem in different ways: 

1. adding your keys to ssh-agent, executing ssh-add ~/.ssh/id_rsa in your command line.
2. adding your keys in settings (open settings browser search for "Use custom SSH keys" and
add your public and private keys).
3. using HTTPS instead SSH (Just use an url in the form [HTTPS://etc.git).](https://etc.git%29./) I will try to clone the HTTPS variant.
```

I think it's better if it did not fail every time it try to load something.

**Comment by Nyan11** [comment]
Will fix *Timeout* in : https://github.com/OpenSmock/Pyramid/pull/84

**Comment by labordep** [comment]
Thanks @Nyan11, I will test a solution for SSH in a script evolution. I will deploy it soon.
