### ISSUE TITLE
Playground is not explicit 

### ISSUE THREAD

**Issue by Nyan11** [OpenSmock/Pyramid#91]
When using the playground, the "self" value depend of the current selection.

* no selection = self is nil
* one selection = self is the selected item
* multiple selection = self is an array containing the selected items

"self" value should be more explicit on the UI.

**Comment by Nyan11** [comment]
Maybe write a comment in the playground section directly.

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/00bbc2ba-6bae-4574-a6c5-2995b4674d5c)
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/6fd731d0-25c2-4e13-8e3a-e850ba845d0e)
![image](https://github.com/OpenSmock/Pyramid/assets/34318678/f6bda5e1-7968-47c2-ae91-538bdf0f9b7b)

**Comment by labordep** [comment]
Without selection, **self** can be the root `BlElement` ?
What do you think about that?

**Comment by labordep** [comment]
> Maybe write a comment in the playground section directly.
> 
> ![image](https://user-images.githubusercontent.com/34318678/271833122-00bbc2ba-6bae-4574-a6c5-2995b4674d5c.png) ![image](https://user-images.githubusercontent.com/34318678/271833159-6fd731d0-25c2-4e13-8e3a-e850ba845d0e.png) ![image](https://user-images.githubusercontent.com/34318678/271833186-f6bda5e1-7968-47c2-ae91-538bdf0f9b7b.png)

Good idean, it can be this : 

```smalltalk
"When using this playground "self" value depend of the context :
    - No selection = self is the root element
    - One selection = self is the selected element
    - Multiple selection = self is an array containing selected items"

self
````

**Comment by labordep** [comment]
The risk to write a comment is to lost it. 
I think this is good to complete with a tag somewhere to display a helper or a tooltip.

**Comment by Nyan11** [comment]
Tooltip on SpCodePresenter doesn't seem to work 100% of the time.

**Comment by Nyan11** [comment]
ok with 120
