### ISSUE TITLE
Cannot re-save on a tag package

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#94]
1- Create a new projet
2- Configure save in a "Test-Core" where **Test** is a package and **Core** is a tag
3- Save your project
4- Add a rectangle into the project
5- Save the project : error cannot save. If I remove the -Core is can save

**Comment by Nyan11** [comment]
I fix it in :  https://github.com/OpenSmock/Pyramid/pull/95 

Now you can save a project by adding a tag after the package name or not.

For example: saving a class in the package **Test**.

If you do not put any tag after, it will be saved in the **undifined tag**.
If you put an existing tag after the package name (**-Core**), it will be saved in the **Core** tag.
If you put a not existing tag after the package name (**-New-Core**), it will be saved in a new tag **New-Core**.

Attention:
* if the class is saved with a tag, you will not be able to save a project with the **same class** but a **different tag**.
* if you want to save a class in a new package named **Test-Abc**, the current implementation will create a new tag in the package **Test**. A possible fix is to first create the **Test-Abc** using a browser.

**Comment by labordep** [comment]
Thanks @Nyan11 !
I think this is can be better to display the class selector before the package selector (because of each class name is unique in pharo).

**Comment by Nyan11** [comment]
Like this ? 

![image](https://github.com/OpenSmock/Pyramid/assets/34318678/1c2620ee-012a-417c-ba8e-f95d029179f0)

**Comment by Nyan11** [comment]
I prefer the previous version, where you go from package, to class, to method.

Their is a gradation between package that contains classes, class that contains methods and method.

Also when we will add auto-completion of text, the package input will be used before the class input, and the class input before the method input.

**Comment by labordep** [comment]
Ok this is a good argument.
To be useful it will be very nice if when I'm typing a class, the package will automatically typed if the class exists.

**Comment by Nyan11** [comment]
Should be fixed by : https://github.com/OpenSmock/Pyramid/pull/98.
Delete when https://github.com/OpenSmock/Pyramid/pull/98 is merged
