### ISSUE TITLE
Pyramid settings section

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Pyramid#99]
In reference of #83, write a dedicated Pyramid settings section in Pharo settings browser.
Provide an access from : 

- [x] - The Pyramid main menu
- [x] - Each Pyramid window

**Comment by labordep** [comment]
Missing: open the settings from a Pyramid window.

**Comment by labordep** [comment]
To do that I suggest to have a simple settings button near the project configuration button (with same icon as in the pyramid library menu and execute same action).

**Comment by Nyan11** [comment]
ok with 123
